export const LOGIN_OTP_VERIFICATION_REQUEST = 'LOGIN_OTP_VERIFICATION_REQUEST';
export const LOGIN_OTP_VERIFICATION_SUCCESS = 'LOGIN_OTP_VERIFICATION_SUCCESS';
export const LOGIN_OTP_VERIFICATION_FAIL = 'LOGIN_OTP_VERIFICATION_FAIL';
